name: Rust Cargo build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Checkout 📥
        uses: actions/checkout@v4

      - name: Build 🛠
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Upload binaries 📤
        uses: actions/upload-artifact@v4
        with:
          path: |
            target/**/release/*.exe
            resources/**
            shaders/**
